# Generated by Django 4.2.8 on 2026-04-03 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenGem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('gem_type', models.CharField(choices=[('natural', 'Natural'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('spiritual', 'Spiritual'), ('local', 'Local Experience')], max_length=20)),
                ('description', models.TextField()),
                ('why_special', models.TextField(help_text='What makes this place unique')),
                ('accessibility_level', models.IntegerField(help_text='1=Easy, 5=Very Difficult', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('entry_fee_npr', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('entry_fee_foreigner_npr', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('best_time_visit', models.CharField(max_length=200)),
                ('visit_duration_hours', models.FloatField()),
                ('crowd_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('rating', models.FloatField(default=4.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('region', models.CharField(choices=[('kathmandu', 'Kathmandu Valley'), ('northeast', 'Northeast (Ilam, Jhapa)'), ('central', 'Central (Pokhara, Chitwan)'), ('west', 'West (Dhulikhel, Narayanghat)'), ('northwest', 'Northwest (Gorkha, Manang)'), ('east', 'East (Bhaktapur, Namobuddha)')], max_length=50)),
                ('description', models.TextField()),
                ('altitude', models.CharField(choices=[('lowland', 'Lowland (< 500m)'), ('mid', 'Mid Hills (500-2000m)'), ('highland', 'Highland (2000-4000m)'), ('alpine', 'Alpine (> 4000m)')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('best_time_visit', models.CharField(help_text='e.g., October-November', max_length=200)),
                ('weather_info', models.TextField()),
                ('distance_from_kathmandu_km', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('travel_time_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('primary_attraction', models.CharField(max_length=200)),
                ('popularity_score', models.IntegerField(default=5, help_text='1-10 scale', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('bus', 'Bus'), ('jeep', 'Jeep/Taxi'), ('flight', 'Flight'), ('train', 'Train'), ('hiking', 'Hiking'), ('private_vehicle', 'Private Vehicle')], max_length=20)),
                ('distance_km', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('local_cost_npr', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('local_cost_description', models.CharField(blank=True, max_length=100, null=True)),
                ('comfort_level', models.IntegerField(help_text='1=Basic, 5=Luxury', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('frequency', models.CharField(help_text="e.g., 'Daily 6AM-6PM' or 'On demand'", max_length=100)),
                ('operator', models.CharField(blank=True, help_text='Bus company, airline, etc.', max_length=200, null=True)),
                ('booking_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='locations.location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='locations.location')),
            ],
            options={
                'ordering': ['source', 'destination', 'transport_type'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['region'], name='locations_l_region_a0b6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['altitude'], name='locations_l_altitud_cfe6ef_idx'),
        ),
        migrations.AddField(
            model_name='hiddengem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_gems', to='locations.location'),
        ),
        migrations.AddIndex(
            model_name='transportoption',
            index=models.Index(fields=['source', 'destination'], name='locations_t_source__ee31a1_idx'),
        ),
        migrations.AddIndex(
            model_name='transportoption',
            index=models.Index(fields=['transport_type'], name='locations_t_transpo_3d2df2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transportoption',
            unique_together={('source', 'destination', 'transport_type')},
        ),
        migrations.AddIndex(
            model_name='hiddengem',
            index=models.Index(fields=['location'], name='locations_h_locatio_457b83_idx'),
        ),
        migrations.AddIndex(
            model_name='hiddengem',
            index=models.Index(fields=['gem_type'], name='locations_h_gem_typ_b1fd1d_idx'),
        ),
    ]
