# Generated by Django 6.0.3 on 2026-04-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='emoji',
            field=models.CharField(default='🏔️', help_text='Emoji to represent the location', max_length=10),
        ),
    ]
