# Generated by Django 4.2.8 on 2026-04-03 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tips', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('number_of_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('budget_level', models.CharField(choices=[('low', 'Budget (< NPR 2000/day)'), ('mid', 'Mid-range (NPR 2000-5000/day)'), ('luxury', 'Luxury (> NPR 5000/day)')], max_length=20)),
                ('interests', models.JSONField(default=list, help_text='List of interests: adventure, culture, trekking, relaxation, etc.')),
                ('estimated_total_budget_npr', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_breakdown', models.JSONField(blank=True, default=dict, help_text='Breakdown: accommodation, food, transport, activities, etc.')),
                ('group_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('travelers_type', models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('group', 'Group')], default='solo', max_length=50)),
                ('ai_prompt', models.TextField(blank=True, help_text='The prompt sent to OpenAI')),
                ('ai_response', models.JSONField(blank=True, default=dict, help_text='Raw response from OpenAI API')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('saved', 'Saved'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('destination_primary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries_primary', to='locations.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(help_text="e.g., 'Kathmandu Exploration'", max_length=200)),
                ('description', models.TextField()),
                ('accommodation_name', models.CharField(blank=True, max_length=200)),
                ('accommodation_type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('guesthouse', 'Guesthouse'), ('homestay', 'Homestay'), ('lodge', 'Lodge'), ('camping', 'Camping')], max_length=50)),
                ('accommodation_estimated_cost_npr', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('meals_budget_npr', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('activities_budget_npr', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_budget_npr', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('activities', models.JSONField(default=list, help_text='List of activities for the day')),
                ('travel_notes', models.TextField(blank=True)),
                ('packing_tips', models.TextField(blank=True)),
                ('local_tips', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itinerary.itinerary')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
            ],
            options={
                'ordering': ['itinerary', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('trekking', 'Trekking'), ('adventure', 'Adventure'), ('cultural', 'Cultural'), ('food', 'Food Tour'), ('relaxation', 'Relaxation'), ('spiritual', 'Spiritual'), ('shopping', 'Shopping'), ('nightlife', 'Nightlife')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_description', models.CharField(blank=True, max_length=300)),
                ('estimated_cost_npr', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_minutes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tips', models.TextField(blank=True, help_text='Local tips, what to bring, etc.')),
                ('importance_level', models.CharField(choices=[('must', 'Must-See'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='recommended', max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_details', to='itinerary.itineraryday')),
                ('related_hidden_gem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tips.localexperience')),
                ('related_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
            ],
            options={
                'ordering': ['day', 'order', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('reminder', 'Reminder'), ('warning', 'Warning'), ('tip', 'Tip'), ('custom', 'Custom Note')], default='custom', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='itinerary.itinerary')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['itinerary'], name='itinerary_i_itinera_e511cf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='itineraryday',
            index=models.Index(fields=['itinerary', 'day_number'], name='itinerary_i_itinera_c942f5_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryday',
            index=models.Index(fields=['location'], name='itinerary_i_locatio_69ae24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('itinerary', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='itineraryactivity',
            index=models.Index(fields=['day'], name='itinerary_i_day_id_e8bd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryactivity',
            index=models.Index(fields=['activity_type'], name='itinerary_i_activit_9a21d8_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['status'], name='itinerary_i_status_510c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['session_id'], name='itinerary_i_session_11d99a_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['budget_level'], name='itinerary_i_budget__9862a4_idx'),
        ),
    ]
