# Generated by Django 4.2.8 on 2026-04-03 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('spring', 'Spring (Feb-May)'), ('summer', 'Summer/Monsoon (Jun-Aug)'), ('autumn', 'Autumn (Sep-Nov)'), ('winter', 'Winter (Dec-Jan)')], max_length=20)),
                ('month', models.IntegerField(unique_for_month='season', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('temperature_range_celsius', models.CharField(help_text="e.g., '15-25°C'", max_length=50)),
                ('rainfall_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('visibility', models.CharField(choices=[('poor', 'Poor'), ('good', 'Good'), ('excellent', 'Excellent')], default='good', max_length=20)),
                ('risks', models.TextField(blank=True, help_text="e.g., 'Landslides, Flight cancellations'")),
                ('recommendations', models.TextField()),
                ('crowd_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('ideal_activities', models.TextField(help_text='Comma-separated activities best suited for this season')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Seasonal Tips',
                'ordering': ['month'],
                'indexes': [models.Index(fields=['season'], name='tips_season_season_e1dd80_idx'), models.Index(fields=['month'], name='tips_season_month_0adbfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('homestay', 'Homestay'), ('workshop', 'Workshop/Class'), ('festival', 'Festival'), ('market', 'Local Market'), ('cuisine', 'Cuisine Experience'), ('trekking', 'Trekking Guide'), ('spiritual', 'Spiritual')], max_length=30)),
                ('description', models.TextField()),
                ('duration_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
                ('cost_per_person_npr', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('group_capacity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_months', models.CharField(blank=True, help_text="e.g., '1,2,3,10,11,12' (1=Jan, 12=Dec)", max_length=100)),
                ('booking_required', models.BooleanField(default=True)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('what_to_expect', models.TextField()),
                ('kids_friendly', models.BooleanField(default=True)),
                ('physical_difficulty', models.IntegerField(default=2, help_text='1=Easy, 5=Very Difficult', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating', models.FloatField(default=4.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_experiences', to='locations.location')),
            ],
            options={
                'ordering': ['-rating', 'category'],
                'indexes': [models.Index(fields=['location'], name='tips_locale_locatio_195549_idx'), models.Index(fields=['category'], name='tips_locale_categor_5e3a0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BudgetTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('activities', 'Activities'), ('shopping', 'Shopping'), ('general', 'General')], max_length=30)),
                ('budget_level', models.CharField(choices=[('budget', 'Budget (< NPR 2000/day)'), ('mid', 'Mid-range (NPR 2000-5000/day)'), ('luxury', 'Luxury (> NPR 5000/day)'), ('all', 'Applicable to All')], default='all', max_length=20)),
                ('content', models.TextField()),
                ('tip_shorthand', models.CharField(help_text='Quick version for UI display', max_length=100)),
                ('effectiveness_score', models.IntegerField(default=7, help_text='How helpful is this tip? (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relevant_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
            ],
            options={
                'ordering': ['-effectiveness_score', 'category'],
                'indexes': [models.Index(fields=['category'], name='tips_budget_categor_cc06c1_idx'), models.Index(fields=['budget_level'], name='tips_budget_budget__4e8fa0_idx')],
            },
        ),
    ]
